secret:
  jwt:
    anonKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
    serviceKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
    secret: your-super-secret-jwt-token-with-at-least-32-characters-long
  smtp:
    username: cybutek.ad@gmail.com
    password: example123456
  dashboard:
    username: supabase
    password: this_password_is_insecure_and_should_be_updated
  db:
    username: app
    password: buS4B7MEDqciLiECkE92RcwSGiKNL1q0xkSow17PCI1UksvuE6AUYvuQAtbdBbQG
    database: app
    db_hostname: cybutek-cnpg-cluster-rw.cloudnative-pg
  analytics:
    apiKey: your-super-secret-and-long-logflare-key

db:
  enabled: false
  image:
    tag: 15.1.0.147
  livenessProbe:
    exec:
      command:
        - pg_isready
        - -U
        - postgres
    initialDelaySeconds: 3
  persistence:
    enabled: false

studio:
  image:
    tag: 2025.06.30-sha-6f5982d
  environment:
    STUDIO_DEFAULT_ORGANIZATION: "My Organization"
    STUDIO_DEFAULT_PROJECT: "My Project"
    SUPABASE_PUBLIC_URL: http://supabase.cybutek.com/
    NEXT_PUBLIC_ENABLE_LOGS: "true"
  livenessProbe:
    httpGet:
      path: /api/profile
      port: 3000
    initialDelaySeconds: 3

auth:
  image:
    tag: v2.176.2-rc.6
  environment:
    DB_HOST: cybutek-cnpg-cluster-rw.cloudnative-pg
    DB_USER: app
    API_EXTERNAL_URL: http://supabase.cybutek.com
    GOTRUE_SITE_URL: http://supabase.cybutek.com
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@example.com"
    GOTRUE_SMTP_HOST: "smtp.example.com"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "your-mail@example.com"

rest:
  image:
    tag: v13.0.4

realtime:
  image:
    tag: v2.39.4
  livenessProbe:
    httpGet:
      path: /
      port: 4000
    initialDelaySeconds: 3
  environment:
    # Override the database hostname if using external database
    DB_HOST: cybutek-cnpg-cluster-rw.cloudnative-pg
    DB_USER: app
    DB_PORT: 5432
    DB_SSL: disable  # disable, allow, prefer, require, verify-ca, verify-full
    DB_AFTER_CONNECT_QUERY: "SET search_path TO _realtime"
    DB_ENC_KEY: supabaserealtime
    PORT: "4000"
    FLY_ALLOC_ID: fly123
    FLY_APP_NAME: realtime
    SECRET_KEY_BASE: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
    ERL_AFLAGS: -proto_dist inet_tcp
    ENABLE_TAILSCALE: "false"
    DNS_NODES: "''"

meta:
  image:
    tag: v0.89.3
  environment:
    # Override the database hostname if using external database
    DB_HOST: cybutek-cnpg-cluster-rw.cloudnative-pg
    DB_USER: app
    DB_PORT: 5432
    DB_DRIVER: postgres
    DB_SSL: disable  # disable, allow, prefer, require, verify-ca, verify-full
    PG_META_PORT: "8080"

storage:
  image:
    tag: v1.24.7
  livenessProbe:
    httpGet:
      path: /status
      port: 5000
    initialDelaySeconds: 3
  persistence:
    enabled: false
  environment:
    # Override the database hostname if using external database
    DB_HOST: cybutek-cnpg-cluster-rw.cloudnative-pg
    DB_USER: app
    DB_PORT: 5432
    DB_DRIVER: postgres
    DB_SSL: disable  # disable, allow, prefer, require, verify-ca, verify-full
    PGOPTIONS: -c search_path=storage,public
    FILE_SIZE_LIMIT: "52428800"
    STORAGE_BACKEND: file  # file, s3
    FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    TENANT_ID: stub
    REGION: stub
    GLOBAL_S3_BUCKET: stub

imgproxy:
  image:
    tag: v3.8.0
  environment:
    IMGPROXY_ENABLE_WEBP_DETECTION: "true"
  livenessProbe:
    exec:
      command:
        - imgproxy
        - health
    initialDelaySeconds: 3
  persistence:
    enabled: false

kong:
  image:
    repository: kong
    tag: 2.8.1
  environment:
    KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
    KONG_LOG_LEVEL: info
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    tls: []
      # - secretName: example-ingress-tls
      #   hosts:
      #     - example.com
    hosts:
      - host: supabase.cybutek.com
        paths:
          - path: /
            pathType: Prefix

analytics:
  image:
    tag: 1.14.2
  livenessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 3
  environment:
    LOGFLARE_NODE_HOST: 127.0.0.1
    DB_HOST: cybutek-cnpg-cluster-rw.cloudnative-pg
    DB_USERNAME: app
    DB_PORT: 5432
    DB_DRIVER: postgresql
    DB_SCHEMA: _analytics
    LOGFLARE_SINGLE_TENANT: "true"
    LOGFLARE_SUPABASE_MODE: "true"
    FEATURE_FLAG_OVERRIDE: multibackend=true

vector:
  image:
    tag: 0.34.0-alpine
  livenessProbe:
    httpGet:
      path: /health
      port: 9001
    initialDelaySeconds: 3
  ## Vector requires logs from the control plane to function.
  ## This is normally stored in /var/log/pods
  ## Modify these values according to your environment.
  volumeMounts:
    - name: pod-logs
      mountPath: /var/log/pods
  volumes:
    - name: pod-logs
      hostPath:
        path: /var/log/pods

functions:
  image:
    tag: v1.67.4
  environment:
    # Override the database hostname if using external database
    DB_HOST: cybutek-cnpg-cluster-rw.cloudnative-pg
    DB_USERNAME: app
    DB_PORT: 5432
    DB_DRIVER: postgresql
    DB_SSL: disable  # disable, allow, prefer, require, verify-ca, verify-full
    HTTP_PROXY: http://10.0.1.25:3128
    HTTPS_PROXY: http://10.0.1.25:3128
    NO_PROXY: 127.0.0.1,localhost,.svc,.cluster.local
    DOCKER_HOST: tcp://localhost:2376
  # Mount user functions
  # volumeMounts:
  #   - name: my_functions
  #     mountPath: /home/deno/functions/main/main
  # volumes:
  #   - name: my_functions
  #     secret:
  #       defaultMode: 733
  #       secretName: my_secret
  #       items:
  #       - key: my_secret.ts
  #         path: name_of_file_in_container.ts
